### ISSUE TITLE
ERROR: failed to start the concentrator

### ISSUE THREAD

**Issue by win7viena** [OpenChirp/lora_gateway_pf#1]
In the journal `journalctl -u lora-gateway-pf` I see a lot of errors: `ERROR: failed to start the concentrator`
Program try`s to restart and again errors.
Here is small copy-paste from journal:

> Apr 23 09:23:33 raspberrypi lora_pkt_fwd[547]: INFO: Auto-quit after 5 non-acknowledged PULL_DATA
> Apr 23 09:23:33 raspberrypi lora_pkt_fwd[547]: ERROR: [main] failed to start the concentrator
> Apr 23 09:23:33 raspberrypi systemd[1]: lora-gateway-pf.service:  Main process exited, code=exited, status=1/FAILURE
> Apr 23 09:23:33 raspberrypi gwrst.sh[559]: Gateway reset successfully
> Apr 23 09:23:33 raspberrypi systemd[1]: lora-gateway-pf.service: Unit entered failed state.
> Apr 23 09:23:33 raspberrypi systemd[1]: lora-gateway-pf.service: Failed with result 'exit-code'.
> Apr 23 09:23:33 raspberrypi systemd[1]: lora-gateway-pf.service: Service hold-off time over, scheduling restart.
> Apr 23 09:23:33 raspberrypi systemd[1]: Stopped packet forwarder.
> Apr 23 09:23:33 raspberrypi systemd[1]: Starting packet forwarder...
> Apr 23 09:23:33 raspberrypi gwrst.sh[565]: Gateway reset successfully
> Apr 23 09:23:34 raspberrypi update_gwid.sh[571]: Gateway_ID set to b827ebFFFEffa9dc in file /etc/lora-gateway-pf/local_c
> Apr 23 09:23:34 raspberrypi systemd[1]: Started packet forwarder.
> Apr 23 09:25:02 raspberrypi lora_pkt_fwd[699]: *** Beacon Packet Forwarder for Lora Gateway ***
> Apr 23 09:25:02 raspberrypi lora_pkt_fwd[699]: Version: 4.0.1
> Apr 23 09:25:02 raspberrypi lora_pkt_fwd[699]: *** Lora concentrator HAL library version info ***
> Apr 23 09:25:02 raspberrypi lora_pkt_fwd[699]: Version: 5.0.1;
> Apr 23 09:25:02 raspberrypi lora_pkt_fwd[699]: ***
> .......
> Apr 23 09:25:02 raspberrypi lora_pkt_fwd[547]: INFO: Auto-quit after 5 non-acknowledged PULL_DATA
> Apr 23 09:25:02 raspberrypi lora_pkt_fwd[547]: ERROR: [main] failed to start the concentrator
> Apr 23 09:25:02 raspberrypi systemd[1]: lora-gateway-pf.service:  Main process exited, code=exited, status=1/FAILURE
> Apr 23 09:25:02 raspberrypi gwrst.sh[559]: Gateway reset successfully
> Apr 23 09:25:02 raspberrypi systemd[1]: lora-gateway-pf.service: Unit entered failed state.
> Apr 23 09:25:02 raspberrypi systemd[1]: lora-gateway-pf.service: Failed with result 'exit-code'.
> Apr 23 09:25:02 raspberrypi systemd[1]: lora-gateway-pf.service: Service hold-off time over, scheduling restart.
> Apr 23 09:25:02 raspberrypi systemd[1]: Stopped packet forwarder.
> Apr 23 09:25:02 raspberrypi systemd[1]: Starting packet forwarder...
> Apr 23 09:25:02 raspberrypi gwrst.sh[565]: Gateway reset successfully

and sometimes it starts:

> Apr 23 09:26:07 raspberrypi lora_pkt_fwd[1121]: INFO: Auto-quit after 5 non-acknowledged PULL_DATA
> Apr 23 09:26:07 raspberrypi lora_pkt_fwd[1121]: INFO: [main] concentrator started, packet can now be received
> Apr 23 09:26:07 raspberrypi lora_pkt_fwd[1121]: INFO: Disabling GPS mode for concentrator's counter...

Using Rpi3

**Comment by ABalanuta** [comment]
Hello @win7viena, This is normal. If you see that it takes a long time until it starts verify that you have a decent power supply. Also what is the LoRa concentrator you are trying this on?

**Comment by win7viena** [comment]
Hello @ABalanuta ,

I try to use RHF0M301 but it seems to me with RAK831 I will have the same errors.
Specifically for this I took a decent Mean Well power supply for 5V/3A, I think the problem is not in it. Also tried to use Rpi2, and surprisingly it gives no errors... 
I did a little research on that :) I tried to use Semtech reference implementation of lora_gateway and packet_forwarder, same errors with Rpi3 and RHF0M301. 
A bit of searching on the Internet I came across several posts:
https://github.com/Lora-net/lora_gateway/issues/26#issuecomment-283089276
But it did not help, errors still appear.
Maybe you have any thoughts about this?

Regards,
Konstantin

**Comment by ABalanuta** [comment]
@win7viena I think it might be that you are not rebooting the RAK831 properly in [our wiki](https://github.com/OpenChirp/docs/wiki/RAK831) for the RAK831 you need to change the reset pin.

> sudo nano /opt/lora-gateway-pf/scripts/gwrst.sh
> change RESET_PIN to 17 instead of 7 and save

**Comment by win7viena** [comment]
@ABalanuta thanks but I always followed the instructions from RHF0M301 https://github.com/OpenChirp/docs/wiki/RHF0M301 and changing the reset pin.

**Comment by ABalanuta** [comment]
@win7viena I could compile a version with lower SPI bus speed but I am afraid that it will penalize the performance. In my tests, the boards take at most  a couple of seconds to start.

**Comment by win7viena** [comment]
@ABalanuta I do not know if this makes sense, packet_forwarder works. Yes, it restarts until the concentrator starts up but then it works.
I was just wondering why these errors occur and how they can be fixed.
Can you check if it works without errors on your hardware? Im using Raspberry Pi 3 Model B V1.2, with latest raspbian stretch distro and RHF0M301.
I also have another Rpi3 and Rpi2, Rpi3 has same errors and Rpi2 works without errors.

**Comment by ABalanuta** [comment]
@win7viena Yes it does show the same behavior. I have RPI3 v1.2

**Comment by mojtaba-esk** [comment]
I had the same issue, I could resolve it by resetting the CE0 and RESET pin before running the forwarder. Here is how i did it:

```#!/bin/bash

echo "Restarting the CE0 pin..."
CSPIN=8
echo "$CSPIN" > /sys/class/gpio/export
sleep 1
echo "out" > /sys/class/gpio/gpio$CSPIN/direction
echo "0" > /sys/class/gpio/gpio$CSPIN/value
sleep 1
echo "1" > /sys/class/gpio/gpio$CSPIN/value
echo "Done\n"
sleep 1

echo "Restarting the Concentrator..."
RSTPIN=17
echo "$RSTPIN" > /sys/class/gpio/export
sleep 1
echo "out" > /sys/class/gpio/gpio$RSTPIN/direction
echo "1" > /sys/class/gpio/gpio$RSTPIN/value
sleep 1
echo "0" > /sys/class/gpio/gpio$RSTPIN/value
echo "Done\nLaunching the forwarder..."
sleep 2

cd /PATH_TO_THE_GATEWAY_CODES/packet_forwarder/ && ./lora_pkt_fwd
```

Save this code in a shell file, change the path according to your own settings and make sure to run it with `sudo`
The full article can be found [here](https://www.mojiot.com/blog/resolved-error-main-failed-to-start-the-concentrator/)
